"""AprilTag board layout loading and bundle-PnP helpers."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Sequence, Tuple

import cv2
import numpy as np
import yaml


@dataclass(frozen=True)
class AprilTagBoardLayout:
    name: str
    family: str
    tag_size_m: float
    board_size_m: Tuple[float, float]
    tile_size_m: float
    pitch_m: float
    marker_fraction: float
    black_marker_edge_gap_m: float
    tags_corners_board_m: Dict[int, np.ndarray]
    tags_T_board_tag: Dict[int, np.ndarray]

    def contains(self, tag_id: int) -> bool:
        return tag_id in self.tags_corners_board_m

    def corners_board_m(self, tag_id: int) -> np.ndarray:
        return self.tags_corners_board_m[tag_id]


def load_apriltag_board_yaml(path: Path | str) -> AprilTagBoardLayout:
    """Load an AprilTag board YAML generated by make_apriltag_grid_pdf.py."""
    with open(path, "r") as f:
        data = yaml.safe_load(f)

    if data.get("schema") != "robot_cam_calib.apriltag_board.v1":
        raise ValueError(f"Unsupported AprilTag board schema in {path}.")
    if data.get("units") != "mm":
        raise ValueError(f"Only millimeter board YAML is currently supported: {path}.")

    geometry = data["geometry"]
    tag_size_m = float(geometry["tag_size_mm"]) * 0.001
    board_size_m = tuple(float(v) * 0.001 for v in geometry["board_size_mm"])
    corners_by_id: Dict[int, np.ndarray] = {}
    T_by_id: Dict[int, np.ndarray] = {}
    for tag in data["tags"]:
        tag_id = int(tag["id"])
        corners_by_id[tag_id] = np.asarray(tag["corners_board_mm"], dtype=np.float32) * 0.001
        T_by_id[tag_id] = np.asarray(tag["T_board_tag"], dtype=np.float64)
        T_by_id[tag_id][:3, 3] *= 0.001

    return AprilTagBoardLayout(
        name=str(data["name"]),
        family=str(data["family"]),
        tag_size_m=tag_size_m,
        board_size_m=(board_size_m[0], board_size_m[1]),
        tile_size_m=float(geometry["tile_size_mm"]) * 0.001,
        pitch_m=float(geometry["pitch_mm"]) * 0.001,
        marker_fraction=float(geometry["marker_fraction"]),
        black_marker_edge_gap_m=float(geometry["black_marker_edge_gap_mm"]) * 0.001,
        tags_corners_board_m=corners_by_id,
        tags_T_board_tag=T_by_id,
    )


def _detection_tag_id(det: Any) -> int:
    if isinstance(det, dict):
        if "tag_id" in det:
            return int(det["tag_id"])
        return int(det["id"])
    return int(getattr(det, "tag_id"))


def _detection_corners(det: Any) -> np.ndarray:
    if isinstance(det, dict):
        if "corners" in det:
            return np.asarray(det["corners"], dtype=np.float32)
        if "lb-rb-rt-lt" in det:
            raise ValueError(
                "The board YAML uses pupil_apriltags Detection.corners order. "
                "Pass dict['corners'] in that order, not 'lb-rb-rt-lt'."
            )
    return np.asarray(getattr(det, "corners"), dtype=np.float32)


def collect_board_pnp_correspondences(
    detections: Iterable[Any],
    board: AprilTagBoardLayout,
    min_tags: int = 1,
) -> Tuple[np.ndarray, np.ndarray, list[int]]:
    """Stack 3D/2D correspondences for bundle PnP from board YAML and detections."""
    obj_pts = []
    img_pts = []
    used_ids = []

    for det in detections:
        tag_id = _detection_tag_id(det)
        if not board.contains(tag_id):
            continue
        corners = _detection_corners(det)
        if corners.shape != (4, 2):
            raise ValueError(f"Detection for tag {tag_id} has corners shape {corners.shape}, expected (4, 2).")
        obj_pts.append(board.corners_board_m(tag_id))
        img_pts.append(corners)
        used_ids.append(tag_id)

    if len(used_ids) < min_tags:
        raise ValueError(f"Only {len(used_ids)} board tags detected; need at least {min_tags}.")

    return np.vstack(obj_pts).astype(np.float32), np.vstack(img_pts).astype(np.float32), used_ids


def square_tag_pose_ambiguity(
    obj_pts: np.ndarray,
    img_pts: np.ndarray,
    K: np.ndarray,
    D: Optional[np.ndarray] = None,
) -> Optional[float]:
    """Reprojection-error ratio between the two IPPE_SQUARE poses of one square tag.

    Four coplanar points admit two poses that mirror each other about the plane
    normal. Both reproject onto nearly the same pixels, so a reprojection-error
    threshold cannot separate them: a flipped pose passes the same gate a correct
    one does. The ratio of the runner-up's error to the winner's does separate
    them -- near 1.0 the reported pose is a coin flip, and large means the winner
    is well isolated.

    Returns None when the correspondence set is not a single tag-frame square, so
    multi-tag boards fall through unaffected.
    """
    obj = np.asarray(obj_pts, dtype=np.float64).reshape(-1, 3)
    if obj.shape[0] != 4:
        return None
    # IPPE_SQUARE requires a square centred on the origin in z=0, ordered
    # (-h, h), (h, h), (h, -h), (-h, -h). That is exactly the tag-frame corner
    # order the board YAML stores, but a tag inside a grid is offset from the
    # board origin and would silently violate it.
    if not np.allclose(obj[:, 2], 0.0, atol=1e-9):
        return None
    if not np.allclose(obj.mean(axis=0), 0.0, atol=1e-9):
        return None
    half = float(np.abs(obj[:, :2]).max())
    expected = np.array([[-half, half], [half, half], [half, -half], [-half, -half]])
    if not np.allclose(obj[:, :2], expected, atol=1e-6):
        return None

    dist_coeffs = np.zeros((5, 1), dtype=np.float64) if D is None else np.asarray(D, dtype=np.float64)
    try:
        _n, _rvecs, _tvecs, errors = cv2.solvePnPGeneric(
            obj.astype(np.float64),
            np.asarray(img_pts, dtype=np.float64).reshape(-1, 2),
            np.asarray(K, dtype=np.float64),
            dist_coeffs,
            flags=cv2.SOLVEPNP_IPPE_SQUARE,
        )
    except cv2.error:
        return None
    if errors is None:
        return None
    errs = np.asarray(errors, dtype=np.float64).reshape(-1)
    if errs.size < 2:
        return float("inf")  # only one pose fits: unambiguous
    best, second = np.sort(errs)[:2]
    if best <= 1e-12:
        return float("inf")
    return float(second / best)


def estimate_board_pose_bundle_pnp(
    detections: Sequence[Any],
    board: AprilTagBoardLayout,
    K: np.ndarray,
    D: Optional[np.ndarray] = None,
    min_tags: int = 1,
) -> Tuple[np.ndarray, list[int]]:
    """Estimate X_CamBoard from all detected board tags with one bundle PnP solve."""
    obj_pts, img_pts, used_ids = collect_board_pnp_correspondences(detections, board, min_tags=min_tags)
    dist_coeffs = np.zeros((5, 1), dtype=np.float64) if D is None else np.asarray(D, dtype=np.float64)
    success, rvec, tvec = cv2.solvePnP(
        obj_pts,
        img_pts,
        np.asarray(K, dtype=np.float64),
        dist_coeffs,
        flags=cv2.SOLVEPNP_ITERATIVE,
    )
    if not success:
        raise RuntimeError("cv2.solvePnP failed for AprilTag board.")

    rvec, tvec = cv2.solvePnPRefineLM(
        obj_pts,
        img_pts,
        np.asarray(K, dtype=np.float64),
        dist_coeffs,
        rvec,
        tvec,
    )
    R_cam_board, _ = cv2.Rodrigues(rvec)
    X_cam_board = np.eye(4)
    X_cam_board[:3, :3] = R_cam_board
    X_cam_board[:3, 3] = tvec.reshape(3)
    return X_cam_board, used_ids
