asset_path: /home/msc-auto/RL_sweep/tasks/Sweep/2/assets/dustpan_smooth_entry/object_mesh_scaled_final.obj
usd_dir: /home/msc-auto/RL_sweep/tasks/Sweep/2/assets/dustpan_smooth_entry
usd_file_name: object_mesh_scaled_final.usd
force_usd_conversion: true
make_instanceable: true
mass_props:
  mass: 0.1
  density: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: null
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: 1000.0
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: 8
  solver_velocity_iteration_count: 0
  sleep_threshold: 0.005
  stabilization_threshold: 0.0025
collision_props:
  collision_enabled: true
  contact_offset: 0.002
  rest_offset: 0.0
  torsional_patch_radius: null
  min_torsional_patch_radius: null
mesh_collision_props:
  usd_func: pxr.UsdPhysics:MeshCollisionAPI
  physx_func: pxr.PhysxSchema:PhysxConvexDecompositionCollisionAPI
  mesh_approximation_name: convexDecomposition
  hull_vertex_limit: null
  max_convex_hulls: 128
  min_thickness: null
  voxel_resolution: null
  error_percentage: null
  shrink_wrap: true
translation: !!python/tuple
- 0.0
- 0.0
- 0.0
rotation: !!python/tuple
- 1.0
- 0.0
- 0.0
- 0.0
scale: !!python/tuple
- 1.0
- 1.0
- 1.0
##
# Generated by MeshConverter on 2026-08-30 at 20:03:42.
##
