n_max: 100
data: succ_grasp # Choices: [init, grasp, succ_grasp, succ_traj, new_template]
succ: null   # Choices: [True, False, None]
qpos: ["grasp"] # Choices: combination from [grasp, pregrasp, squeeze, traj_state, traj_ctrl]

hand:
  mode: visual  # Choices: [visual, collision]

cust_log_dir: ${log_dir}
