#!/usr/bin/env python3
"""Replay a precomputed MANO-retargeted carry trajectory in Isaac Sim.

The full wrist trajectory is fixed before simulation starts.  Every frame
before carry is copied from ``grasp_traj``; during carry only the precomputed
wrist pose changes and all finger targets stay equal to the final grasp
target.  The dynamic object's measured pose is recorded for evaluation and
never feeds back into the wrist command.
"""

from __future__ import annotations

import json
from pathlib import Path
import time

import numpy as np

from ocir.full_traj.metrics import ordered_pose_path_metrics, paired_pose_path_metrics
from ocir.full_traj.reference import FullTrajectoryReference
from ocir.grasp_traj.trajectory_schema import SEGMENT_CARRY, GraspTrajectory, pos_quat_to_matrix
from ocir.isaac import simulate_grasp_traj as base
from ocir.isaac.sim_cli import run_sim_cli_main
from ocir.sim.control_client import request_json
from ocir.sim.isaac_server import DEFAULT_OCIR_DATA_ROOT


DEFAULT_OUT_DIR = DEFAULT_OCIR_DATA_ROOT / "testing/full_traj/isaac_sim"


def log(message: str) -> None:
    print(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] OCIR_FULL_TRAJ_SIM {message}", flush=True)


def _validate_open_loop_trajectory(trajectory_dir: str | Path) -> tuple[GraspTrajectory, FullTrajectoryReference]:
    trajectory = GraspTrajectory.load(trajectory_dir)
    reference = FullTrajectoryReference.load(trajectory_dir)
    carry_rows = np.flatnonzero(trajectory.segment == SEGMENT_CARRY)
    if carry_rows.size == 0:
        raise ValueError("full trajectory has no carry segment")
    carry_start = int(carry_rows[0])
    if carry_start != int(reference.carry_start_step):
        raise ValueError(
            f"full trajectory/reference carry boundary mismatch: {carry_start} != {reference.carry_start_step}"
        )
    if np.any(trajectory.segment[carry_start:] != SEGMENT_CARRY):
        raise ValueError("carry segment must be the final contiguous trajectory segment")
    if carry_start <= 0:
        raise ValueError("open-loop full trajectory requires a completed grasp prefix")
    metadata = trajectory.extra_metadata.get("full_traj", {})
    if metadata.get("control_mode") != "open_loop":
        raise ValueError("trajectory was not generated by the open-loop full_traj generator; regenerate it")

    fixed = np.asarray(reference.fixed_finger_targets, dtype=np.float64)
    if fixed.shape != (len(trajectory.joint_order),):
        raise ValueError("fixed finger target does not match trajectory joint order")
    expected = np.tile(fixed[None], (carry_rows.size, 1))
    if not np.array_equal(trajectory.finger_targets[carry_rows], expected):
        raise ValueError("carry finger targets are not exactly constant")
    if not np.allclose(
        trajectory.hand_pos_camera[carry_start], trajectory.hand_pos_camera[carry_start - 1], atol=1e-10
    ) or not np.allclose(
        trajectory.hand_quat_camera[carry_start], trajectory.hand_quat_camera[carry_start - 1], atol=1e-10
    ):
        raise ValueError("retargeted wrist is discontinuous at carry entry")
    if not np.allclose(
        trajectory.object_pos_camera[carry_start], trajectory.object_pos_camera[carry_start - 1], atol=1e-10
    ) or not np.allclose(
        trajectory.object_quat_camera[carry_start], trajectory.object_quat_camera[carry_start - 1], atol=1e-10
    ):
        raise ValueError("aligned object reference is discontinuous at carry entry")
    return trajectory, reference


def _add_open_loop_report(report: dict, args, trajectory: GraspTrajectory, reference: FullTrajectoryReference) -> dict:
    out_dir = Path(args.out_dir)
    with np.load(out_dir / "object_track.npz", allow_pickle=False) as data:
        actual_pos = np.asarray(data["position_world"], dtype=np.float64)
        actual_quat = np.asarray(data["orientation_world_wxyz"], dtype=np.float64)
        reference_pos = np.asarray(data["reference_position_world"], dtype=np.float64)
        reference_quat = np.asarray(data["reference_orientation_world_wxyz"], dtype=np.float64)
        segments = np.asarray(data["segment"], dtype=np.int8)
    with np.load(out_dir / "finger_track.npz", allow_pickle=False) as data:
        desired_fingers = np.asarray(data["desired_position_rad"], dtype=np.float64)

    runtime_count = segments.size
    carry_mask = segments == SEGMENT_CARRY
    actual = pos_quat_to_matrix(actual_pos[:runtime_count][carry_mask], actual_quat[:runtime_count][carry_mask])
    target = pos_quat_to_matrix(reference_pos[carry_mask], reference_quat[carry_mask])
    fixed = np.asarray(reference.fixed_finger_targets, dtype=np.float64)
    carry_fingers = desired_fingers[carry_mask]
    position_tolerance = float(args.path_position_tolerance)
    orientation_tolerance = np.deg2rad(float(args.path_orientation_tolerance_deg))

    report["task"] = "full_traj_simulation"
    report["full_traj_open_loop"] = {
        "control_mode": "open_loop",
        "wrist_commands_precomputed": True,
        "object_pose_used_for_control": False,
        "carry_start_step": int(reference.carry_start_step),
        "num_carry_frames": int(carry_mask.sum()),
        "source_duration_seconds": float(reference.metadata["source_duration_seconds"]),
        "trajectory_duration_seconds": float(max(carry_mask.sum() - 1, 0) * trajectory.dt),
        "source_frame_start": float(reference.source_frame_index[0]),
        "source_frame_end": float(reference.source_frame_index[-1]),
        "finger_targets_constant": bool(
            carry_fingers.size
            and np.array_equal(carry_fingers, np.tile(fixed[None], (carry_fingers.shape[0], 1)))
        ),
        "time_aligned_path_metrics": paired_pose_path_metrics(actual, target),
        "ordered_path_metrics": ordered_pose_path_metrics(
            actual,
            target,
            position_tolerance_m=position_tolerance,
            orientation_tolerance_rad=orientation_tolerance,
        ),
    }
    (out_dir / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return report


def simulate_full_traj(app, args, progress=None) -> dict:
    trajectory, reference = _validate_open_loop_trajectory(args.trajectory_dir)
    if bool(args.contact_aware_finger_targets):
        raise ValueError("full trajectory requires fixed finger targets; use --no-contact-aware-finger-targets")
    if str(args.carry_mode) != base.CARRY_MODE_FRICTION:
        raise ValueError("open-loop object tracking requires a dynamic object; use --carry-mode friction")
    # Do not leave a closed-loop diagnostic from an older run beside the new
    # open-loop outputs when reusing an existing isaac_sim directory.
    stale_controller_track = Path(args.out_dir) / "controlled_wrist_track.npz"
    if stale_controller_track.exists():
        stale_controller_track.unlink()
    report = base.simulate_grasp_traj(app, args, progress=progress)
    return _add_open_loop_report(report, args, trajectory, reference)


def build_parser():
    parser = base.build_parser()
    parser.description = __doc__
    parser.set_defaults(
        out_dir=DEFAULT_OUT_DIR,
        contact_aware_finger_targets=False,
        carry_mode=base.CARRY_MODE_FRICTION,
    )
    for action in parser._actions:
        if action.dest in {"contact_aware_finger_targets", "contact_target_lead_rad"}:
            action.help = "Disabled for full_traj: carry finger targets must remain exactly constant."
    group = parser.add_argument_group("open-loop full-trajectory evaluation")
    group.add_argument("--path-position-tolerance", type=float, default=0.008)
    group.add_argument("--path-orientation-tolerance-deg", type=float, default=5.0)
    return parser


def normalize_paths(args) -> None:
    base.normalize_paths(args)
    if args.status or args.shutdown_server:
        return
    if float(args.path_position_tolerance) <= 0.0 or float(args.path_orientation_tolerance_deg) <= 0.0:
        raise ValueError("path evaluation tolerances must be positive")
    _validate_open_loop_trajectory(args.trajectory_dir)
    if bool(args.contact_aware_finger_targets):
        raise ValueError("full trajectory does not permit contact-aware finger target rewriting")
    if str(args.carry_mode) != base.CARRY_MODE_FRICTION:
        raise ValueError("full trajectory requires --carry-mode friction")


def parse_args():
    parser = build_parser()
    args = parser.parse_args()
    base.apply_mode_defaults(args, parser)
    normalize_paths(args)
    return args


def normalize_task_args(params: dict):
    parser = build_parser()
    args = parser.parse_args([])
    for key, value in params.items():
        if hasattr(args, key):
            setattr(args, key, value)
    base.apply_mode_defaults(args, parser)
    normalize_paths(args)
    return args


def run_simulation_task(app, args, progress) -> dict:
    old_log = base.log
    base.log = log
    try:
        return simulate_full_traj(app, args, progress=progress)
    finally:
        base.log = old_log


def register_sim_tasks(registry) -> None:
    registry.register(
        "full_traj_simulation",
        run=run_simulation_task,
        normalize=normalize_task_args,
        description="Replay a precomputed MANO-retargeted wrist carry with a dynamic object.",
    )


def main() -> int:
    args = parse_args()
    if args.status:
        try:
            print(json.dumps(request_json(args.control_host, args.control_port, "GET", "/status", timeout=1.0), indent=2), flush=True)
            return 0
        except Exception as exc:
            print(f"OCIR_FULL_TRAJ_SIM no control server at {args.control_host}:{args.control_port}: {exc}", flush=True)
            return 1
    if args.shutdown_server:
        try:
            print(json.dumps(request_json(args.control_host, args.control_port, "POST", "/shutdown", {}, timeout=2.0), indent=2), flush=True)
            return 0
        except Exception as exc:
            print(f"OCIR_FULL_TRAJ_SIM no control server at {args.control_host}:{args.control_port}: {exc}", flush=True)
            return 1
    old_log = base.log
    base.log = log
    try:
        return run_sim_cli_main(
            args,
            log=log,
            run_batch=simulate_full_traj,
            task="full_traj_simulation",
            log_prefix="OCIR_FULL_TRAJ_SIM",
            restart_hint=(
                "Restart the server with this task module, for example:\n"
                "  scripts/run_isaacsim_conda.sh scripts/sim/start_isaacsim_server.py "
                "--task-module scripts/full_traj/simulate_full_traj.py"
            ),
        )
    finally:
        base.log = old_log


if __name__ == "__main__":
    raise SystemExit(main())
