# Copyright (C) 2025 Dexmate Inc.
#
# This software is dual-licensed:
#
# 1. GNU Affero General Public License v3.0 (AGPL-3.0)
#    See LICENSE-AGPL for details
#
# 2. Commercial License
#    For commercial licensing terms, contact: contact@dexmate.ai

"""Async motion handle for tracking plugin-based motion requests.

Provides the MotionHandle class that monitors motion status events from the
motion plugin and exposes wait(), cancel(), and state properties.

The *motion plugin* is the robot's internal motion controller, running on the
robot-server (not in this client library). A handle is a client-side proxy: it
tracks the lifecycle of a single motion request the plugin is executing on the
robot, surfacing the plugin's status events as local state transitions.

MultiMotionHandle wraps multiple per-component handles for robot-level
move_to_joint_pos() calls.
"""

import threading
from typing import Callable, Literal

from dexcontrol.exceptions import PluginNotAvailableError

MotionState = Literal["accepted", "working", "finished", "cancelled", "error"]

_TERMINAL_STATES: frozenset[MotionState] = frozenset({"finished", "cancelled", "error"})


class MotionHandle:
    """Async handle for a tracked motion request.

    Created by ``ManagedJointComponent.move_to_joint_pos()``. Monitors status
    events from the motion plugin and provides blocking wait, cancel, and state
    inspection.

    The handle is lightweight: it holds a motion_id, a threading Event for
    blocking, and a reference to a cancel callback. No resource leak if
    discarded without calling wait().

    Args:
        motion_id: Client-generated unique identifier for this motion.
        publish_cancel_fn: Callback that publishes a cancel message to the
            motion/target/{component} topic. Accepts the motion_id to cancel.
    """

    def __init__(
        self,
        motion_id: int,
        publish_cancel_fn: Callable[[int], None],
    ) -> None:
        self._motion_id = motion_id
        self._publish_cancel_fn = publish_cancel_fn
        self._state: MotionState = "accepted"
        self._message: str = ""
        self._done_event = threading.Event()
        self._lock = threading.Lock()
        # True once any status message arrives from the plugin. Used by wait()
        # to distinguish "plugin not running" from "motion still in flight".
        self._status_received: bool = False

    @property
    def motion_id(self) -> int:
        """Unique identifier generated by the client."""
        return self._motion_id

    @property
    def is_done(self) -> bool:
        """True if motion reached a terminal state (finished, cancelled, or error)."""
        return self._state in _TERMINAL_STATES

    @property
    def state(self) -> MotionState:
        """Current motion state."""
        return self._state

    @property
    def message(self) -> str:
        """Optional message from the plugin (e.g., error details)."""
        return self._message

    def wait(self, timeout: float | None = None) -> MotionState:
        """Block until motion reaches a terminal state.

        Args:
            timeout: Maximum time to wait in seconds. None = wait indefinitely.

        Returns:
            The terminal MotionState.

        Raises:
            PluginNotAvailableError: If the wait times out and no status
                message was ever received from the plugin. Distinguishes
                "plugin not running on the robot-server" from "motion
                still in flight".
            TimeoutError: If timeout exceeded after the plugin has begun
                emitting status but before a terminal state arrives.
            RuntimeError: If the motion ended with an error state.
        """
        if not self.is_done:
            if not self._done_event.wait(timeout=timeout):
                if not self._status_received:
                    raise PluginNotAvailableError(
                        f"No status response from the motion plugin for motion "
                        f"{self._motion_id} within {timeout}s. The motion "
                        f"plugin may not be running on the robot-server."
                    )
                raise TimeoutError(
                    f"Motion {self._motion_id} did not complete within {timeout}s. "
                    "Consider increasing the wait timeout. If the motion is "
                    "moving too slowly, consider increasing velocity_scale on "
                    "the motion command."
                )
        if self._state == "error":
            raise RuntimeError(f"Motion {self._motion_id} failed: {self._message}")
        return self._state

    def cancel(self) -> None:
        """Cancel this motion.

        Publishes a cancel message to motion/target/{component} with the
        cancel_motion_id field set. No-op if the motion is already in a
        terminal state.
        """
        if self.is_done:
            return
        self._publish_cancel_fn(self._motion_id)

    def _update_state(self, state: MotionState, message: str = "") -> None:
        """Update the motion state (called by the status dispatcher).

        This is an internal method called when a status event matching this
        motion_id is received from the plugin.

        Args:
            state: New motion state.
            message: Optional message from the plugin.
        """
        with self._lock:
            self._state = state
            self._message = message
            self._status_received = True
            if state in _TERMINAL_STATES:
                self._done_event.set()


# Priority for picking the "worst" terminal state across components.
_STATE_SEVERITY: dict[MotionState, int] = {
    "finished": 0,
    "accepted": 1,
    "working": 1,
    "cancelled": 2,
    "error": 3,
}


class MultiMotionHandle:
    """Combined handle for a robot-level tracked motion across multiple components.

    Wraps per-component MotionHandles and provides a single wait() that blocks
    until every component reaches a terminal state.

    Args:
        handles: Mapping of component name to its MotionHandle.
    """

    def __init__(self, handles: dict[str, MotionHandle]) -> None:
        self._handles = handles

    @property
    def is_done(self) -> bool:
        """True if all component motions have reached a terminal state."""
        return all(h.is_done for h in self._handles.values())

    @property
    def state(self) -> MotionState:
        """Aggregate state — the worst state across all components."""
        return max(
            (h.state for h in self._handles.values()),
            key=lambda s: _STATE_SEVERITY.get(s, 1),
        )

    def wait(self, timeout: float | None = None) -> MotionState:
        """Block until all component motions reach a terminal state.

        Each component's remaining budget is the original *timeout* minus the
        wall-clock time already spent waiting on previous components, so the
        total wait never exceeds *timeout* seconds.

        Args:
            timeout: Maximum total wall-clock time in seconds. None = wait
                indefinitely.

        Returns:
            The worst MotionState across all components.

        Raises:
            TimeoutError: If timeout exceeded before all motions complete.
            PluginNotAvailableError: If any component never heard from the
                plugin (surfaced after all siblings have been observed).
            RuntimeError: If any component ended in an error state (surfaced
                after all siblings have been observed).
        """
        # Compute an absolute deadline so per-handle waits share the budget.
        import time

        deadline_ts = None if timeout is None else time.monotonic() + timeout

        # A failed/absent component must not abort the loop — we still need to
        # observe the terminal state of every sibling motion. Defer the most
        # severe failure and raise it only after all handles have been waited on.
        deferred: Exception | None = None
        for name, handle in self._handles.items():
            if deadline_ts is None:
                remaining = None
            else:
                remaining = deadline_ts - time.monotonic()
                if remaining <= 0:
                    raise TimeoutError(
                        f"Multi-component motion timed out waiting for '{name}' "
                        f"(timeout={timeout}s)"
                    )
            try:
                handle.wait(timeout=remaining)
            except TimeoutError:
                raise TimeoutError(
                    f"Multi-component motion timed out waiting for '{name}' "
                    f"(timeout={timeout}s)"
                ) from None
            except (PluginNotAvailableError, RuntimeError) as exc:
                # Prefer surfacing a missing-plugin failure (infra-level) over a
                # per-motion error; otherwise keep the first failure seen.
                if deferred is None or isinstance(exc, PluginNotAvailableError):
                    deferred = exc

        if deferred is not None:
            raise deferred

        return self.state

    def cancel(self) -> None:
        """Cancel all component motions that have not yet finished."""
        for handle in self._handles.values():
            handle.cancel()

    @property
    def message(self) -> str:
        """Aggregated messages from all components that have a non-empty message."""
        parts = [
            f"{name}: {h.message}" for name, h in self._handles.items() if h.message
        ]
        return "; ".join(parts)
